// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ItemsColumns holds the columns for the "items" table.
	ItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "tx_type_id", Type: field.TypeInt64, Nullable: true},
		{Name: "sku", Type: field.TypeString, Nullable: true},
		{Name: "title", Type: field.TypeString, Nullable: true},
		{Name: "sub_title", Type: field.TypeString, Nullable: true},
		{Name: "status_id", Type: field.TypeInt64, Nullable: true},
		{Name: "no_index", Type: field.TypeBool, Nullable: true},
		{Name: "item_category_id", Type: field.TypeInt64, Nullable: true},
		{Name: "base_on_sale_price", Type: field.TypeBool, Nullable: true},
		{Name: "retail_price", Type: field.TypeFloat64, Nullable: true},
		{Name: "sale_price", Type: field.TypeFloat64, Nullable: true},
		{Name: "shipping_profile_id_num", Type: field.TypeInt64, Nullable: true},
		{Name: "optimization_id_num", Type: field.TypeInt64, Nullable: true},
		{Name: "qty", Type: field.TypeInt64, Nullable: true},
		{Name: "maximum_order_qty", Type: field.TypeInt64, Nullable: true},
		{Name: "pkg_width", Type: field.TypeFloat64, Nullable: true},
		{Name: "pkg_height", Type: field.TypeFloat64, Nullable: true},
		{Name: "pkg_length", Type: field.TypeFloat64, Nullable: true},
		{Name: "pkg_weight", Type: field.TypeFloat64, Nullable: true},
		{Name: "short_desc", Type: field.TypeString, Nullable: true},
		{Name: "descr", Type: field.TypeString, Nullable: true},
		{Name: "image_url1", Type: field.TypeString, Nullable: true},
		{Name: "image_url2", Type: field.TypeString, Nullable: true},
		{Name: "image_url3", Type: field.TypeString, Nullable: true},
		{Name: "image_url4", Type: field.TypeString, Nullable: true},
		{Name: "image_url5", Type: field.TypeString, Nullable: true},
		{Name: "condition", Type: field.TypeString, Nullable: true},
		{Name: "brand", Type: field.TypeString, Nullable: true},
		{Name: "gender", Type: field.TypeString, Nullable: true},
		{Name: "age_group", Type: field.TypeString, Nullable: true},
		{Name: "color", Type: field.TypeString, Nullable: true},
		{Name: "size", Type: field.TypeString, Nullable: true},
		{Name: "uxm_item_id_num", Type: field.TypeInt64, Nullable: true},
		{Name: "sent", Type: field.TypeBool, Nullable: true},
		{Name: "sent_at", Type: field.TypeTime, Nullable: true},
		{Name: "has_error", Type: field.TypeBool, Nullable: true},
		{Name: "last_log_id", Type: field.TypeInt64, Nullable: true},
		{Name: "feed_response", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "keywords", Type: field.TypeString, Nullable: true},
		{Name: "sync", Type: field.TypeBool, Nullable: true},
		{Name: "user_id", Type: field.TypeString, Nullable: true},
		{Name: "shipping_profile_id", Type: field.TypeString, Nullable: true},
		{Name: "optimization_id", Type: field.TypeString, Nullable: true},
		{Name: "uxm_item_id", Type: field.TypeString, Nullable: true},
		{Name: "parent_id", Type: field.TypeString, Nullable: true},
		{Name: "item_type_id", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "uid", Type: field.TypeString, Unique: true},
		{Name: "is_parent", Type: field.TypeBool, Nullable: true},
	}
	// ItemsTable holds the schema information for the "items" table.
	ItemsTable = &schema.Table{
		Name:       "items",
		Columns:    ItemsColumns,
		PrimaryKey: []*schema.Column{ItemsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "api_key", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeBool, Nullable: true, Default: false},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ItemsTable,
		UsersTable,
	}
)

func init() {
}
