// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/khanakia/entautoslow/ent/schema"
	"github.com/khanakia/entautoslow/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[2].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(bool)
}
